sudo: required
services:
  - docker

before_install:
  - docker build -t phuctranlv/learn-docker -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true phuctranlv/learn-docker npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "learn-docker"
  env: "LearnDocker-env"
  bucket_name: "elasticbeanstalk-us-west-1-237841522464"
  bucket_path: "learn-docker"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:$AWS_SECRET_KEY
